services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://devops_user:devops_pass@db:5432/devops_db
   
    volumes:
      - ./app:/app/app       # Espelha o código em tempo real (ótimo para dev)
      - ./tests:/app/tests   # Espelha os arquivos de teste

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_pass
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@devops.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: